app = "jp-valkyrie"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Flyfile"

[[services]]
  internal_port = 443
  protocol = "tcp"
  [[services.ports]]
    port = "443"