# test this goreleaser config with:
# - cd chisel
# - goreleaser --skip-publish --rm-dist --config .github/goreleaser.yml
builds:
  - id: chisel
    binary: chisel
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/jpillora/chisel/share.BuildVersion={{.Version}}
    flags:
      - -trimpath
    goos:
      - linux
      - windows
    goarch:
      - amd64
  - id: chisel-garble
    binary: chisel-garble
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - ""
    gobinary: "garble-literals"
archives:
  - format: gz
    files:
      - none*
release:
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
