# test this file with
#   goreleaser release --config goreleaser.yml --clean --snapshot
version: 2
builds:
  - id: chisel
    binary: chisel
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/jpillora/chisel/share.BuildVersion={{.Version}}
    flags:
      - -trimpath
    goos:
      - linux
      - windows
    goarch:
      - amd64

  - id: chisel-garble
    binary: chisel-garble
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - ""
    gobinary: "garble-literals"
nfpms:
  - maintainer: "https://github.com/{{ .Env.GITHUB_USER }}"
    formats:
      - deb
      - rpm
      - apk
archives:
  - id: chisel
    builds: [chisel]
    format: gz
    name_template: chisel_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - none*
  - id: chisel-garble
    builds: [chisel-garble]
    format: gz
    name_template: chisel-garble_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - none*
release:
  draft: true
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
